### ISSUE TITLE
question!

### ISSUE THREAD

**Issue by toshibochan** [jderehag/rpi-rfsniffer#1]
how to setup and how to chose the pin for transmitter and receiver?

**Comment by jderehag** [comment]
What du you mean exactly?
If you have a look at https://github.com/jderehag/rpi-rfsniffer/blob/master/README.rst
You would see that it defaults to tx on pin 11 and rx on pin 13.
And if you would have tried "rfsniffer - -help"  you would have noticed that you can overide those with - -rxpin or - -txpin respectively. 

Does that answer your question?

**Comment by jderehag** [comment]
Since no reply, closing this issue.
