### ISSUE TITLE
Pin numbering

### ISSUE THREAD

**Issue by Nickduino** [jderehag/rpi-rfsniffer#3]
Which one is it?

Broadcom GPIO numbers, board numbers ?

**Comment by jderehag** [comment]
As it says in the help text: "The RPi **boardpin** where the RF receiver is attached"
I.e its using board numbers and operating in board mode: RPi.GPIO.setmode(RPi.GPIO.BOARD).

But since this question have been asked a few times I will clarify the help text..

**Comment by Nickduino** [comment]
If I may make a suggestion, a simple image would do:

![image](https://user-images.githubusercontent.com/9784237/52269357-219a9200-293e-11e9-8128-f6b19cff3381.png)
