### ISSUE TITLE
can't get event with rfsniffer in raspberry pi4

### ISSUE THREAD

**Issue by mmm286** [jderehag/rpi-rfsniffer#8]
Hi!
I've bought a transmitter and receiver (https://mary.codes/blog/home_automation/quick_and_dirty_fan_hacking_with_raspberry_pi/)
When I do rfsniffer don't detect any event. 
Do you know if it's compatible with rasp 4?
Thanks

**Comment by jderehag** [comment]
I have not tested it on rpi4 unfortunatly.
But seems others have managed to get it to work if you look at #6.
Although those changes seems weird that it would have an impact on rpi4, but could be worth a try.

**Comment by jderehag** [comment]
Closed by misstace.
